### ISSUE TITLE
Uninformative test failure

### ISSUE THREAD

**Issue by jaminfine** [cboulanger/eventrecorder#7]
Upon playing a test that fails, the message is often uninformative. On screen a pop up will say:
```
Cannot read property 'fireEvent' of undefined
```

A warning is logged in the console with slightly more information:
```
008882 cboulanger.eventrecorder.player.Qooxdoo[1041-0]: TypeError: Cannot read property 'fireEvent' of undefined
eval at <anonymous>
```

It would be helpful if the test failure message would say which line of the test script caused the failure.

**Comment by cboulanger** [comment]
True, this is unhelpful. If you set the environment variable "qx.debug" to true and use one of the qooxdoo loggers, you should be seeing much more, since the logging is quite extensive (see [here](https://github.com/cboulanger/eventrecorder/blob/master/source/class/cboulanger/eventrecorder/player/Abstract.js#L660)). However, information on the line of the script could certainly be added to the [command execution](https://github.com/cboulanger/eventrecorder/blob/master/source/class/cboulanger/eventrecorder/player/Abstract.js#L715) and for [macros](https://github.com/cboulanger/eventrecorder/blob/master/source/class/cboulanger/eventrecorder/player/Abstract.js#L683) and [imports](https://github.com/cboulanger/eventrecorder/blob/master/source/class/cboulanger/eventrecorder/player/Abstract.js#L709).

**Comment by cboulanger** [comment]
@jaminfine Error reporting should be improved by https://github.com/cboulanger/eventrecorder/commit/3932f970205743a7a4ec363984ac302ba4c983a6 , please report if this solves your problem and close the issue if it does.

**Comment by jaminfine** [comment]
This makes it much clearer where a test fails! This definitely solves the issue
